version: '2'
services:
    web-app:
        container_name: mecu_webservice
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:3000
        depends_on:
            - database
        env_file:
            - app-variables.env

    database:
        container_name: mecu_postgresdb
        image: sacdallago/mecu-postgres
        ports:
            - 54322:5432
